# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\fedju\Downloads\vista_home.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# # run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from TorreDiCerrano.Registrazione.VistaRegistrazione import VistaRegistrazione
from TorreDiCerrano.Login.VistaLogin import VistaLogin
from PyQt5.QtGui import QFont



class Ui_HOME(object):
    def setupUi(self, HOME):
        HOME.setObjectName("HOME")
        HOME.resize(1267, 913)
        HOME.setStyleSheet("background-color: rgba(255, 255, 120, 50);")
        self.centralwidget = QtWidgets.QWidget(HOME)
        self.centralwidget.setObjectName("centralwidget")
        self.login = QtWidgets.QPushButton(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(900, 20, 171, 45))
        self.login.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 75 16pt \"Arial\";\n"
"color: rgb(255, 255, 255);\n"
"")
        self.login.setObjectName("login")
        self.login.clicked.connect(self.go_vista_login)
        self.registrati = QtWidgets.QPushButton(self.centralwidget)
        self.registrati.setGeometry(QtCore.QRect(1080, 20, 171, 45))
        self.registrati.setStyleSheet("font: 75 16pt \"Arial\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 0);")
        self.registrati.setObjectName("registrati")
        self.registrati.clicked.connect(self.go_vista_registrazione)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 50, 991, 841))
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("background-color: rgba(255, 168, 29, 0);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("images/torre_di_cerrano[325].jpg"))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(1050, 350, 181, 161))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/travel-1677347_1920.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(1050, 580, 191, 121))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("images/sea-3704014_1920.jpg"))
        self.label_3.setScaledContents(True)
        self.label_3.setWordWrap(False)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(70, 270, 450, 111))
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(255, 255, 255, 0);\n"
"font: 40pt \"Papyrus\";")
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(360, 90, 500, 91))
        self.label_4.setStyleSheet("color: rgb(51, 102, 255);\n"
"font: 100 90pt \"Papyrus\";\n background-color: rgba(255, 168, 29, 0);")
        self.label_4.setObjectName("label_4")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(40, 30, 270, 145))
        self.listWidget.setMinimumSize(QtCore.QSize(261, 0))
        self.listWidget.setStyleSheet("font: 12pt \"Papyrus\";\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(178, 225, 255);\n"
"selection-color: rgb(170, 255, 0);")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)

        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        HOME.setCentralWidget(self.centralwidget)

        self.retranslateUi(HOME)
        QtCore.QMetaObject.connectSlotsByName(HOME)

    def retranslateUi(self, HOME):
        _translate = QtCore.QCoreApplication.translate
        HOME.setWindowTitle(_translate("HOME", "MainWindow"))
        self.login.setText(_translate("HOME", "Login"))
        self.registrati.setText(_translate("HOME", "Registrati"))
        self.label_5.setText(_translate("HOME", "Resort Torre di Cerrano"))
        self.label_4.setText(_translate("HOME", " Benvenuto  "))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)

        item = self.listWidget.item(0)
        item.setText(_translate("HOME", "hotel"))
        item = self.listWidget.item(1)
        item.setText(_translate("HOME", "bungalow"))
        item = self.listWidget.item(2)
        item.setText(_translate("HOME", "ristorante"))
        item = self.listWidget.item(3)
        item.setText(_translate("HOME", "stabilimento balneare"))
        item = self.listWidget.item(4)
        item.setText(_translate("HOME", "campi sportivi"))
        item = self.listWidget.item(5)
        item.setText(_translate("HOME", "area ricreativa"))
        item = self.listWidget.item(6)
        item.setText(_translate("HOME", "piscine"))
        item = self.listWidget.item(7)
        item.setText(_translate("HOME", "centro benessere"))
        item = self.listWidget.item(8)
        item.setText(_translate("HOME", "noleggio mezzi elettrici"))
        self.listWidget.setSortingEnabled(__sortingEnabled)

    def go_vista_registrazione(self):
        self.vista_registrazione = VistaRegistrazione()
        self.vista_registrazione.show()

    def go_vista_login(self):
        self.vista_login = VistaLogin()
        self.vista_login.show()
